### ISSUE TITLE
remove quotes in data in context column (confusing)

### ISSUE THREAD

**Issue by Garrafao** [Garrafao/WUGs#16]
https://github.com/Garrafao/WUGs/blob/main/durel_system/upload_formats/test_project/uses/adventure.csv

Quotes are not needed, it looks like the context, must be quoted, but it shouldn't.

**Comment by AinaIanemahy** [comment]
This issue should be moved to durel.

**Comment by Garrafao** [comment]
Is this data still used in DURel? (be it for internal development or published for users?)

**Comment by Garrafao** [comment]
became obsolete as data was moved to DURel system repository
