### ISSUE TITLE
test_uug dataset not usable

### ISSUE THREAD

**Issue by Tuo-ZHANG** [Garrafao/WUGs#18]
Please try to upload both the uses file and the instances file into the system and make sure they can be uploaded. Currently, both two files have problems.

**Comment by Tuo-ZHANG** [comment]
the instances file for the test_english dataset also needs to be fixed

**Comment by Tuo-ZHANG** [comment]
the uses file for the test_english dataset also causes problems.  look for example, the line 72 of the file https://github.com/Garrafao/WUGs/blob/main/durel_system/upload_formats/test_english/uses/contemplation_nn.csv

**Comment by Garrafao** [comment]
The issues were solved, and tested by uploading to the DURel system.
