### ISSUE TITLE
The number of excluded nodes

### ISSUE THREAD

**Issue by akutuzov** [Garrafao/WUGs#2]
It is my understanding that  the [exclude_nodes.py](https://github.com/Garrafao/WUGs/blob/main/scripts/exclude_nodes.py) script removes from the graph the nodes which either have more than 50% of 0 judgments or which do not have valid judgments at all.
The nodes here are usages (sentences containing target words).

Based on this understanding, for each target word I would expect the number of excluded nodes plus the number of preserved nodes to be equal to the number of the original nodes (number of usages). However, this is not the case. With my data, after the processing is over, I am looking at the files in the `stats` subdirectory and observe cases like this:

Excluded nodes (from `excluded_nodes.csv`): **15**
Preserved nodes (from `stats_grouping.csv`): **10**

However, there were **22** unique sentences for this word in the original data. I see in the graphs and in the clusters, that there are indeed 10 sentences taken into account, so 12 sentences were discarded, not 15. I observe this for more than one target word. In extreme cases, the number of excluded nodes actually is _higher than the total number of sentences for a word_.

I did not yet look deep into the code, but may be I am just misunderstanding something?

**Comment by Garrafao** [comment]
it seems this is a bug occurring if nodes_zero and nodes_nan overlap. It should be fixed now.

**Comment by akutuzov** [comment]
Thanks! Indeed, this is solved now.
