### ISSUE TITLE
WUG Pipeline Sub-processes

### ISSUE THREAD

**Issue by AinaIanemahy** [Garrafao/WUGs#27]
What are the separate sub-processes of the pipeline? Which values are calculated in these sub-processes? What is the format of the output values?

**Comment by Garrafao** [comment]
the sub processes can be seen here:

https://github.com/Garrafao/WUGs/blob/main/scripts/run_system2.sh

it is basically:

source $scriptsdir/data2join.sh
source $scriptsdir/data2annotators.sh
source $scriptsdir/data2agr.sh
source $scriptsdir/use2graph.sh
source $scriptsdir/judgments2graph.sh
source $scriptsdir/graph2cluster2.sh
source $scriptsdir/graph2stats.sh
source $scriptsdir/graph2plot2.sh

To each of the shell scripts corresponds one Python script. These are described in the readme.
