### ISSUE TITLE
Wrong file paths in various shell scripts

### ISSUE THREAD

**Issue by Garrafao** [Garrafao/WUGs#48]
I have noticed only now (after running `bash -e test.sh`) that paths in various files were modified with @AinaIanemahy 's latest pull request:

https://github.com/Garrafao/WUGs/pull/47

This concerns:

data2join.sh
data2annotators.sh
data2graph.sh
graph2stats.sh
graph2cluster2.sh
graph2plot2.sh
graph2filter.sh

I have reverted these changes with commit [7e33047](https://github.com/Garrafao/WUGs/commit/7e33047da8137d02e95a3f86fe26b9d4e4d277d8) to make `test.sh` run through. Please note that these scripts are used for DURel-unrelated purposes. Hence, they should not be modified. Instead I recommend duplicating these scripts for your purposes with suffix  "_system" (easy solution) or generalizing the paths as input arguments to the relevant shell scripts. Whether your solution works for all purposes can be checked by running `bash -e test.sh` (which should be run before pushing to the repository anyway).

**Comment by AinaIanemahy** [comment]
Sorry for the toss-up. I thought that you had checked before pulling, but I should have made that clearer.
I have now fixed all the problems and restored the compatibility with the new durel workings in commit [8d04736](https://github.com/Garrafao/WUGs/commit/8d047360c962350307586fc0dae65b98c33a3c60). I have made sure to run the test script before pushing.

I have also updated the test file to include my new scripts, so maybe you can check it on your side (also because I am not sure whether we have the same data in test_uug1). 

I have made the following changes:

- Adapt new scripts to fix path problems
- Adapt graph2filter.sh, graph2cluster2.sh, graph2plot2.sh, data2graph.sh to work both with and without original/filtered/clustered distinction
- Add necessary parameters to parameters files
- Reinclude data2agr in run_system2.sh
- Add graph2filter.sh to run_uug2.sh (this was missing before)

**Comment by AinaIanemahy** [comment]
I will also go back to DURel and rename all references to annotations.csv back to judgments.csv. This will create inconsistencies in variable naming inside DURel but that concerns fewer people than the inconsistencies between DURel and WUGs.

**Comment by AinaIanemahy** [comment]
Please close this after running the test if I have solved everything. @Garrafao

**Comment by Garrafao** [comment]
I ran `bash -e test.sh`. I observed output like this though: 

- `test_uug/graphs//plane_nn`. For now, this works as Bash ignores duplicate slashes. But, for avoiding future problems, could you please adjust these paths?
- There is some error in `map_data_structure.sh`:
```
timestamp
2024-12-28_11:28:47
parameterfile: scripts/parameters_system2.sh
dir: test_uug
isanonymize: False
summarystatistic: median
nonvalue: 0.0
edgestyles: weight
threshold: 2.5
position: spring
modes: full
scripts/map_data_structure.sh
*_uses.csv
data install_packages.sh lib LICENSE packages_wsbm.yml packages.yml README.md results scripts test.sh test_usg test_uug test_uug1 update-git.sh
cp: Ziel 'test_uug/data/病毒/uses.csv': Ist kein Verzeichnis
```

**Comment by Garrafao** [comment]
Also, do the scripts `run_system.sh` and `run_system2.sh` have any relevance for the DURel tool after commit [8d04736](https://github.com/Garrafao/WUGs/commit/8d047360c962350307586fc0dae65b98c33a3c60)?

**Comment by AinaIanemahy** [comment]
RE map_data_structure.sh - See my comment above

> map_data_structure.sh won't work yet because the test data does not have the right format. Please tell me if I should include this!

map_data_structure.sh was the script you introduced to map the DURel output format to the other format, so it is doing exactly what it is meant to do. The test data simply does not fit the script so I need to add test data that does.

**Comment by AinaIanemahy** [comment]
> Also, do the scripts `run_system.sh` and `run_system2.sh` have any relevance for the DURel tool after commit [8d04736](https://github.com/Garrafao/WUGs/commit/8d047360c962350307586fc0dae65b98c33a3c60)?

No, they don't.

**Comment by Garrafao** [comment]
> RE map_data_structure.sh - See my comment above
> 
> > map_data_structure.sh won't work yet because the test data does not have the right format. Please tell me if I should include this!
> 
> map_data_structure.sh was the script you introduced to map the DURel output format to the other format, so it is doing exactly what it is meant to do. The test data simply does not fit the script so I need to add test data that does.

It would be great if you could add such test data! Maybe under `test_uug_system`?

**Comment by AinaIanemahy** [comment]
I have added the test data in commit 9378294a6023ac3088348873f63a4d3115a3d3da

**Comment by AinaIanemahy** [comment]
I have fixed the // paths in commit 02a57b258e1158641e1632ea6db7c9a83cdfd2c5. Instead, the scripts now use an if condition.

**Comment by AinaIanemahy** [comment]
I have removed run_system.sh and the parameters file belonging to it. (8216d5cac77c18a3c67fb7c35616271f4d8886e2)

I have updated the test to remove run_system.sh and use the new pipeline only.

run_system2.sh still seems to be used in some jupyter script, which is why I haven't deleted it yet.

**Comment by Garrafao** [comment]
I have pulled and ran `bash -e test.sh`:
```
timestamp
2024-12-29_15:50:34
scripts/data2join.sh
test_uug/data/Aufkommen
test_uug/data/demá
test_uug/data/Manschette
test_uug/data/plane_nn
test_uug/data/überspannen
test_uug/data/uses.csv
Traceback (most recent call last):
  File "/mount/projekte50/projekte/cik/users/dominik/WUGs/scripts/data2join.py", line 7, in <module>
    with open(uses, encoding='utf-8') as csvfile: 
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test_uug/data/uses.csv/uses.csv'
```
 Did you run the test script before pushing?

**Comment by AinaIanemahy** [comment]
Yes, I did run it and yes it did and still does complete successfully.

From the logs, it looks like your directory is different from the version that is online.

> test_uug/data/demá
test_uug/data/Manschette
test_uug/data/plane_nn
test_uug/data/überspannen
test_uug/data/uses.csv

I do not have demá and plane_nn in there and the uses.csv shouldn't be there at all. Did you maybe accidentally copy the file?

**Comment by Garrafao** [comment]
`test_uug/` indeed had some files locally that were ignored through an unintended statement in `.gitignore`. The pipeline (presumably) didn't run through because of `test_uug/data/uses.csv` which (presumably) was created unintentionally by some other script at some point. After fixing this with commit [595c0ce](https://github.com/Garrafao/WUGs/commit/595c0ce87580e4f3ae823f11497824d1ef34835f), the test script now runs through. I am observing though output like this, which I assume is intended:
```
test_uug_system/graphs/clustered/Vorwort
The file test_uug_system/stats/stats.csv cannot be found.
The file test_uug_system/stats/stats_groupings.csv cannot be found.
The file test_uug_system/stats/stats_agreement.csv cannot be found.
```
